#!/usr/bin/env bash
# clones my AirBnB_clone_v2 on your web-01 server
# configures the file web_flask/0-hello_route.py to serve its content from the route /airbnb-onepage/ on port 5000.

git clone https://github.com/bekalue/AirBnB_clone_v2.git
cd AirBnB_clone_v2
sudo sed -i "s@app.route('/')@app.route('/airbnb-onepage/')@" web_flask/0-hello_route.py


# Test it
python3 -m web_flask.0-hello_route

# curl 127.0.0.1:5000/airbnb-onepage/
