#!/usr/bin/env bash
# config

# vars
GUNICORN=$(which gunicorn)

# the systemd service file
SERVICE_CONFIG=/etc/systemd/system/airbnb.service
CONFIG="[Unit]
Description=Gunicorn instance to serve AirBnB_clone_v4
After=network.target

[Service]
User=$USER
Group=www-data
WorkingDirectory=/home/ubuntu/AirBnB_clone_v4
Environment=\"PATH=/home/ubuntu/AirBnB_clone_v4\"
Environment=HBNB_MYSQL_USER=hbnb_dev
Environment=HBNB_MYSQL_PWD=hbnb_dev_pwd
Environment=HBNB_MYSQL_HOST=localhost
Environment=HBNB_MYSQL_DB=hbnb_dev_db
Environment=HBNB_TYPE_STORAGE=db
Environment=HBNB_ENV=dev
ExecStart=$GUNICORN --workers 3 --bind 0.0.0.0:5003 --access-logfile /tmp/airbnb-access.log --error-logfile /tmp/airbnb-error.log web_dynamic.2-hbnb:app

[Install]
WantedBy=multi-user.target"
echo "$CONFIG" | sudo tee $SERVICE_CONFIG > /dev/null

# Create log files if they do not exist
if [ ! -f /tmp/airbnb-access.log ]; then
    sudo touch /tmp/airbnb-access.log
fi

if [ ! -f /tmp/airbnb-error.log ]; then
    sudo touch /tmp/airbnb-error.log
fi

# Set permissions and ownership for log files
sudo chown $USER:www-data /tmp/airbnb-access.log /tmp/airbnb-error.log
sudo chmod 664 /tmp/airbnb-access.log /tmp/airbnb-error.log

# Reload the systemd daemon
sudo systemctl daemon-reload

# Start the airbnb service
sudo systemctl start airbnb

# Enable the service to start automatically at boot
sudo systemctl enable airbnb

# Check the status of the service
sudo systemctl status airbnb

